### ISSUE TITLE
Discussion details supplement

### ISSUE THREAD

**Issue by RicardoMiles** [UoB-COMSM0110/2024-group-1#6]
Thank you very much for your active participation and valuable input. I have uploaded the document from this discussion to the /docs folder, which will serve as a reference framework for future discussions. If anyone has time to help supplement detailed discussions or add discussion items, that would be great.
@A-PS1999 @JThakral20 @erer1022 @Doctor-TOTORO

**Comment by A-PS1999** [comment]
As part of the pull request I just made for some of the game framework code, I've also added a document I wrote summarizing the meeting we had today. Consequently, since that pull request is ready for @JThakral20 or another team member to review before merging, I've moved this ticket also to 'In Review'.
